# Numpy

In [1]:
import numpy as np

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
a = np.zeros(100)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
a = np.ones(100)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
a = np.full(100, 3)
a

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [5]:
#python3 -c "import numpy; nupmy.info(numpy.add)"

#### 5. Поменять 2 строки в матрице

In [6]:
a = np.random.random((5, 5))
print(a)
i, j = 1, 2
a[[i, j]] = a[[j, i]]
print(a)

[[0.14498144 0.06331839 0.4453144  0.14101482 0.20711029]
 [0.9805887  0.44360859 0.71276018 0.30443571 0.13118079]
 [0.10413482 0.69436607 0.8124369  0.05691856 0.06186873]
 [0.76061644 0.37555363 0.32106707 0.84318694 0.03156166]
 [0.12991664 0.13126104 0.27401493 0.67749081 0.16445831]]
[[0.14498144 0.06331839 0.4453144  0.14101482 0.20711029]
 [0.10413482 0.69436607 0.8124369  0.05691856 0.06186873]
 [0.9805887  0.44360859 0.71276018 0.30443571 0.13118079]
 [0.76061644 0.37555363 0.32106707 0.84318694 0.03156166]
 [0.12991664 0.13126104 0.27401493 0.67749081 0.16445831]]


#### 6. Создать вектор со значениями от 10 до 100

In [7]:
a = np.arange(10, 100 + 1)
a

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [8]:
a = a[::-1]
a

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [9]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [10]:
a = np.arange(1, 6)
b = np.zeros((3+1)*(5-1)+1)
b[::3+1] = a
b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [11]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [12]:
a = np.random.random((3, 3, 3))
a

array([[[0.76775745, 0.58307516, 0.67388093],
        [0.95507035, 0.32467633, 0.81664711],
        [0.46969372, 0.43688257, 0.20286556]],

       [[0.04619973, 0.54727822, 0.83418854],
        [0.7513164 , 0.36716781, 0.79288448],
        [0.80521934, 0.17791385, 0.60634054]],

       [[0.79154417, 0.66665285, 0.94394071],
        [0.92015383, 0.53291882, 0.37555864],
        [0.84632632, 0.69224373, 0.40697024]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [13]:
a = np.random.random((10, 10))
print(a)
print(a.min(), a.max())


[[0.01353886 0.15924276 0.65483651 0.40984792 0.08872052 0.79239882
  0.77780935 0.92059867 0.24852689 0.61312543]
 [0.42678636 0.09529103 0.52436885 0.42834112 0.9218142  0.02243395
  0.74732794 0.55468334 0.1242042  0.01381726]
 [0.57312427 0.52219752 0.43024015 0.15925824 0.18050888 0.61646028
  0.89680656 0.66355728 0.799637   0.34720031]
 [0.31923539 0.69578048 0.56799819 0.23714418 0.42451253 0.45446564
  0.00467198 0.32153445 0.25880823 0.34391705]
 [0.35081705 0.72813597 0.35182913 0.64977203 0.47771842 0.80319518
  0.62025909 0.78531575 0.39030677 0.39345937]
 [0.76059069 0.63241781 0.64642456 0.58083405 0.72483437 0.47347072
  0.25527273 0.64208483 0.96280361 0.71657384]
 [0.87051233 0.68626436 0.62184673 0.6012845  0.44994487 0.94262579
  0.33109215 0.86670229 0.97622169 0.08960728]
 [0.41222675 0.79129965 0.61732718 0.6891629  0.28471404 0.00502111
  0.38535745 0.59465793 0.09999557 0.35701164]
 [0.71031398 0.77492501 0.68627973 0.74013668 0.72660743 0.55373554
  0.66776812

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [14]:
a = np.random.random(30)
print(a.mean())

0.5081186519159879


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [15]:
a = np.ones(25).reshape(5, 5)
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класСное преобразование в numpy (не идет в зачет)


In [16]:
a.transpose() #ну да - не знаю, что написать

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [17]:
a = np.diag(np.array([1, 2, 2, 4]), k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [18]:
a = np.ones((8, 8))
a[::2, 1::2] = 0
a[1::2, ::2] = 0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [19]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [20]:
a = np.tile([[1, 0], [0, 1]], (4, 4))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [21]:
a = np.random.randint(1, 5, (5, 3))
b = np.random.randint(1, 5, (3, 2))
print(a)
print(b)
print(np.dot(a, b))

[[3 3 4]
 [4 1 4]
 [3 3 1]
 [1 1 3]
 [1 2 3]]
[[3 1]
 [3 3]
 [1 1]]
[[22 16]
 [19 11]
 [19 13]
 [ 9  7]
 [12 10]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [22]:
a = np.random.uniform(0, 10, 10)
mask = ((a >= 3) & (a <= 8))
a[mask] *= -1
a

array([ 1.92347963, -4.27633195,  2.28890946, -3.46316274, -3.38803038,
        8.65459973, -5.916382  , -4.56750904, -6.8222167 ,  0.47576822])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [23]:
a = np.zeros((5, 5))
a += np.arange(0, 5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 24. Есть генератор, сделать с его помощью массив

In [24]:
def generate():
    for x in range(1, 20, 2):
        yield x
        
a = np.fromiter(generate(), dtype = int)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [25]:
a = np.linspace(0, 1, 10 + 2)
a = a[1:11]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [26]:
a = np.random.random(10)
a.sort()
a

array([0.0268419 , 0.18300796, 0.18509061, 0.51993918, 0.54252692,
       0.76994391, 0.80088741, 0.89302541, 0.90440132, 0.9139202 ])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [27]:
a = np.arange(1, 10)
b = np.arange(1, 10)
print(np.allclose(a, b))

True


#### 28. Сделать массив неизменяемым

In [28]:
a.flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [29]:
n = 4
a = np.random.randint(1, 15, 7)
print(a)
a = sorted(a, reverse=True)
a = a[:n]
print(a)


[ 1 11  1  1 14 12  8]
[14, 12, 11, 8]


#### 30. Заменить максимальный элемент на ноль

In [30]:
a = np.random.randint(1, 10, 7)
print(a)
a[a.argmax()] = 0
print(a)

[7 4 1 4 4 1 7]
[0 4 1 4 4 1 7]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [31]:
a = np.zeros((10, 10), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))
a

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.


#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [32]:
x = np.arange(8)
y = np.arange(1, 9) - 0.3
c = 1.0 / np.subtract.outer(x, y)
c

array([[-1.42857143, -0.58823529, -0.37037037, -0.27027027, -0.21276596,
        -0.1754386 , -0.14925373, -0.12987013],
       [ 3.33333333, -1.42857143, -0.58823529, -0.37037037, -0.27027027,
        -0.21276596, -0.1754386 , -0.14925373],
       [ 0.76923077,  3.33333333, -1.42857143, -0.58823529, -0.37037037,
        -0.27027027, -0.21276596, -0.1754386 ],
       [ 0.43478261,  0.76923077,  3.33333333, -1.42857143, -0.58823529,
        -0.37037037, -0.27027027, -0.21276596],
       [ 0.3030303 ,  0.43478261,  0.76923077,  3.33333333, -1.42857143,
        -0.58823529, -0.37037037, -0.27027027],
       [ 0.23255814,  0.3030303 ,  0.43478261,  0.76923077,  3.33333333,
        -1.42857143, -0.58823529, -0.37037037],
       [ 0.18867925,  0.23255814,  0.3030303 ,  0.43478261,  0.76923077,
         3.33333333, -1.42857143, -0.58823529],
       [ 0.15873016,  0.18867925,  0.23255814,  0.3030303 ,  0.43478261,
         0.76923077,  3.33333333, -1.42857143]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [33]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [ np.float32, np.float64]:
    print(np.finfo(dtype).min, np.finfo(dtype).max)

-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [34]:
a = np.zeros((15,15))
np.set_printoptions(threshold=15*15)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [35]:
a = np.arange(15)
cur = np.random.uniform(1, 15)
print(cur)
print(a[(np.abs(a - cur)).argmin()])

10.854078793950217
11


#### 36. Преобразовать массив из float в int

In [36]:
a = np.ones(10)
print(a.dtype)
a = a.astype(np.int64)
print(a)

float64
[1 1 1 1 1 1 1 1 1 1]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [37]:
#np.ndenumerate()

#### 38. Случайно расположить p элементов в 2D массив

In [38]:
a = np.zeros((10, 10))
p = 10
np.put(a, np.random.choice(np.arange(10*10), p), np.random.randint(1, 10, 1))
a

array([[0., 0., 0., 0., 0., 6., 0., 0., 0., 0.],
       [0., 0., 0., 0., 6., 0., 0., 0., 0., 0.],
       [6., 0., 0., 0., 0., 0., 0., 0., 0., 6.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [6., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 6., 0., 0., 6.],
       [0., 0., 6., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 6., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 39. Отнять среднее из каждой строки в матрице

In [39]:
a = np.random.randint(1, 10, (5, 10))
print(a)
a = a - a.mean(axis = 1, keepdims = True)
print(a)

[[1 2 5 2 4 4 2 6 6 9]
 [7 6 9 4 1 2 2 5 6 1]
 [6 2 3 3 2 9 4 3 2 5]
 [9 1 2 6 3 7 1 6 9 1]
 [3 4 7 8 2 7 2 6 6 9]]
[[-3.1 -2.1  0.9 -2.1 -0.1 -0.1 -2.1  1.9  1.9  4.9]
 [ 2.7  1.7  4.7 -0.3 -3.3 -2.3 -2.3  0.7  1.7 -3.3]
 [ 2.1 -1.9 -0.9 -0.9 -1.9  5.1  0.1 -0.9 -1.9  1.1]
 [ 4.5 -3.5 -2.5  1.5 -1.5  2.5 -3.5  1.5  4.5 -3.5]
 [-2.4 -1.4  1.6  2.6 -3.4  1.6 -3.4  0.6  0.6  3.6]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [40]:
a = np.random.randint(0, 10, (3, 3))
n = 1
print(a)
a = a[a[:, n].argsort()]
print(a)

[[1 7 2]
 [4 7 8]
 [0 0 8]]
[[0 0 8]
 [1 7 2]
 [4 7 8]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [41]:
a = np.random.randint(0, 3, (4, 10))
print(a)
print((~a.any(axis = 0)).any())

[[2 0 1 1 2 0 1 2 1 1]
 [2 0 0 1 2 0 0 0 0 2]
 [0 0 1 1 1 1 0 2 1 0]
 [1 1 1 0 2 2 1 2 0 0]]
False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [42]:
a = np.ones(10)
b = np.random.randint(0, 10, 20)
print(a)
print(b)
a += np.bincount(b, minlength = 10)
a

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 9 5 7 5 1 5 2 0 9 9 4 8 3 9 0 7 9 0 6]


array([4., 3., 2., 2., 2., 4., 2., 3., 2., 6.])

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [43]:
w, h = 10, 10
img = np.random.randint(0, 10, (w, h, 3)).astype(np.ubyte)
col = img[..., 0] * 256 ** 2 + img[..., 1] * 256 + img[..., 2]
print(len(np.unique(col)))

94


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [44]:
a = np.random.randint(1, 10, (2, 2, 2, 2))
print(a)
print(a.sum(axis = -1) + a.sum(axis = -2))
#я вижу, что это не тру, но лучше не придумала

[[[[7 1]
   [2 9]]

  [[2 3]
   [5 9]]]


 [[[5 7]
   [9 1]]

  [[3 5]
   [7 6]]]]
[[[17 21]
  [12 26]]

 [[26 18]
  [18 24]]]
