# ML T-Generation Занятие 2: Data Wrangling Основы работы с векторными данными и визуализацией. NumPy

## Пример задач

Давайте рассмотрим пример решения одной из задач на сайте kaggle и постараемся ее проанализировать.


https://www.kaggle.com/madhulekha/a-comprehensive-solution-to-your-first-ml-problem

Как видите, изучение данных и генерация признаков занимает большую часть решения. Это нормально.

## Numpy

Библиотека предназаченная для работы с массивами. Очевидный вопрос-почему не встроенные массивы python. Давайте сразу на примере посмотрим, почему

In [1]:
import numpy as np  

In [2]:
%timeit [i**2 for i in range(1000)]

1000 loops, best of 5: 251 µs per loop


In [3]:
%timeit np.arange(1000)**2

The slowest run took 1269.46 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.8 µs per loop


Разница существенная

### Справка

В 1995 году программист Jim Hugunin написал библиотеку Numeric для языка Python. Библиотека развивалась при участии многих людей, среди которых были Jim Fulton, David Ascher, Paul DuBois и Konrad Hinsen. Библиотека доступна по сей день, считается вполне стабильной и полной, но устаревшей.

Предлагалось добавить Numeric в стандартную библиотеку языка Python, но Гвидо Ван Россум (автор Python) чётко дал понять, что код в его тогдашнем состоянии было невозможно поддерживать.

Кроме того, библиотека Numeric медленно обрабатывала большие массивы данных.

На основе библиотеки Numeric была создана библиотека NumArray. Код Numeric был полностью переписан.

Библиотека NumArray обрабатывала большие массивы данных быстрее библиотеки Numeric, но малые массивы обрабатывала медленнее.

Некоторое время использовалась и библиотека Numeric, и библиотека NumArray. Последняя версия Numeric (v24.2) была выпущена 11 ноября 2005 года. Последняя версия NumArray (v1.5.2) вышла 24 августа 2006 года. Библиотека NumArray более не рекомендуется к использованию.

В начале 2005 года программист Трэвис Олифант захотел объединить сообщество вокруг одного проекта и для замены библиотек Numeric и NumArray создал библиотеку NumPy. NumPy был создан на основе кода Numeric. Код Numeric был переписан так, чтобы его было легче поддерживать, и в библиотеку можно было добавить новые возможности. Возможности NumArray были добавлены в NumPy.

Изначально NumPy был частью библиотеки SciPy. Чтобы позволить другим проектам использовать библиотеку NumPy, её код был помещён в отдельный пакет.

Исходный код NumPy находится в открытом доступе. Существует большое количество документации. Имеется даже подробный «Путеводитель по NumPy».

NumPy v1.3.0 выпущен 5 апреля 2009 года и поддерживает Python v2.6. Поддержка Python v3 была добавлена начиная с версии 1.5.0.

http://www.numpy.org

### Шпаргалка

В Numpy большой набор стандартных функций, которые помогают реализовывать даже самые сложные операции. Для того что бы не тратить время на написание собственных функций, будет полезно иметь шпаргалку с основными полезными

In [4]:
from IPython.display import Image
Image('numpy.png') 

In [5]:
# немного хитростей jupyter - двойным табом, можно вызвать документацию
# np.

In [6]:
a = np.array([1,3,4,5])
a

array([1, 3, 4, 5])

смотрим размерность массива

In [7]:
a.ndim

1

In [8]:
# TASK: создать двумерный/трехмерный массив
a = np.array([[1, 2], [1,2]])
a

array([[1, 2],
       [1, 2]])

In [9]:
b = np.array([[1,3,4,5],[1,3,4,5]])
b

array([[1, 3, 4, 5],
       [1, 3, 4, 5]])

### Создание массивов

**На практике мы редко добавляем элементы по одному и нужно создавать матрицу/массив нужной размерности**

- Равномерно распределенные элементы:

In [10]:
a = np.arange(10) # 0 .. n-1  (!)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b = np.arange(1, 11, 2) # начало, конец(не включая), шаг
b

array([1, 3, 5, 7, 9])

- по числу элементов:

In [12]:
c = np.linspace(0, 1, 6)   # начало, конец, количество точек
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [13]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

- Часто встречающиеся массивы:

In [14]:
a = np.ones((3, 3))  
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

In [16]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

* `np.random` генерация случайных чисел:

In [18]:
a = np.random.rand(4)
a  

array([0.41854326, 0.36722101, 0.53367797, 0.47928752])

In [19]:
np.random.seed(42)
b = np.random.randn(10)
b  

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

### Основные типы данных NumPy

In [20]:
import numpy as np

In [21]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

Точка после числа означает, что это тип данных `float64`

In [22]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

In [23]:
c = np.array(["1", 2, 3])
c.dtype

dtype('<U1')

In [24]:
c[1]

'2'

In [25]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Прочие типы данных:

- Комплексные числа

In [27]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

dtype('complex128')

 - Bool

In [28]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

- Строки

На строки память выделяется "жадно" - по максимальному числу литер в строке. 
В этом примере на каждую строку выделяется по 7 литер, и тип данных - 'U7'

In [29]:
f = np.array([(1,23,4), 'Hello', 'Hallo',])
f.dtype

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


dtype('O')

### Индексирование массивов и срезы

В целом так же, как со встроенными последовательностями Python (например, как со списками).

**Индексирование**

In [30]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a[0], a[2], a[-1]

(0, 2, 9)

Работает и популярный в Python способ отражения массива:

In [32]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Для многомерных массивов индексы - это кортежи целых чисел. Кортеж, по сути - неизменяемый список.

In [33]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [34]:
%timeit a[1, 1]

The slowest run took 93.28 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 5: 153 ns per loop


In [35]:
%timeit a[1][1]

The slowest run took 55.56 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 357 ns per loop


In [36]:
a[2, 1] = 10 
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [37]:
a[1]

array([0, 1, 0])

**Срезы**

In [38]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a[2:9:3] # [начало:конец:шаг]

array([2, 5, 8])

Последний индекс не включается

In [40]:
a[:4]

array([0, 1, 2, 3])

Можно совмещать присваивание и срез:

In [41]:
a = np.arange(10)


In [42]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [43]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
b[::-1]

array([4, 3, 2, 1, 0])

In [45]:
a[5:]

array([5, 6, 7, 8, 9])

In [46]:
np.random.seed(3)
a = np.random.randint(0, 20, 15)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 12,  7, 14, 17])

In [47]:
(a % 3 == 0)

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True,  True, False, False, False])

In [48]:
mask = (a % 3 == 0)
extract_from_a = a[mask] 
extract_from_a           

array([ 3,  0,  9,  6,  0, 12])

Индексирование маской может быть очень полезным для присваивания значений части элементов массива:

In [49]:
a[a % 3 == 0] = -1
a

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, -1,  7, 14, 17])

Индексирование массивом целых чисел

In [50]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
a[[2, 3, 2, 4, 2]]  # тут должен быть питоновский лист

array([20, 30, 20, 40, 20])

In [52]:
a[[9, 7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

In [53]:
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])
idx.shape
idx

array([[3, 4],
       [9, 7]])

In [54]:
a[idx]

array([[3, 4],
       [9, 7]])

### Умножение матриц и столбцов

In [55]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)

print("Матрица A:\n", a)
print("Матрица B:\n", b)
print("Результат умножения функцией:\n", r1)
print("Результат умножения методом:\n", r2)

Матрица A:
 [[1 0]
 [0 1]]
Матрица B:
 [[4 1]
 [2 2]]
Результат умножения функцией:
 [[4 1]
 [2 2]]
Результат умножения методом:
 [[4 1]
 [2 2]]


In [56]:
a@b

array([[4, 1],
       [2, 2]])

Матрицы в `NumPy` можно умножать и на векторы:

In [57]:
c = np.array([1, 2])
r3 = b.dot(c)

print("Матрица:\n", b)
print("Вектор:\n", c)
print("Результат умножения:\n", r3)

Матрица:
 [[4 1]
 [2 2]]
Вектор:
 [1 2]
Результат умножения:
 [6 6]


__Обратите внимание:__ операция __`*`__ производит над матрицами покоординатное умножение, а не матричное!

In [58]:
r = a * b

print("Матрица A:\n", a)
print("Матрица B:\n", b)
print("Результат покоординатного умножения через операцию *:\n", r)
a

Матрица A:
 [[1 0]
 [0 1]]
Матрица B:
 [[4 1]
 [2 2]]
Результат покоординатного умножения через операцию *:
 [[4 0]
 [0 2]]


array([[1, 0],
       [0, 1]])

Более подробно о матричном умножении в `NumPy`
см. [документацию](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

In [59]:
# Задание: написать функции выводящие минимум для массива, сумму


In [60]:

# Ваш код тут

In [61]:
a = np.array([1,2,3])


# Внимание. Самостоятельная работа

# Задание по numpy

In [62]:
# 0. Создать нулевой вектор с 5 значений на 5 позиции 5
# Ваш код здесь
a = np.zeros(6)
a[5] = 5
a

array([0., 0., 0., 0., 0., 5.])

In [63]:
# 1. Создать матрицу 3*3 со значениями от 0 до 8
# Ваш код здесь
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
# 2. Найти индексы не нулевых элементов в массиве [1,2,0,0,4,0]
# Ваш код здесь
a = [1, 2, 0, 0, 4, 0]
a = np.nonzero(a)
a

(array([0, 1, 4]),)

In [65]:
# 3. Матрица 3*3*3 с рандомными значениями
# Ваш код здесь
a = np.random.random((3, 3, 3))
a

array([[[0.35390507, 0.49263593, 0.91330145],
        [0.76582638, 0.97364827, 0.40236064],
        [0.55277195, 0.30636063, 0.58661997]],

       [[0.27492011, 0.45460777, 0.75766525],
        [0.81757073, 0.25758529, 0.89306511],
        [0.71842202, 0.0206145 , 0.14271733]],

       [[0.32530618, 0.8089292 , 0.39899095],
        [0.42470161, 0.41371868, 0.7871385 ],
        [0.71356575, 0.02311757, 0.31576725]]])

In [66]:
# 4. Матриа 10 на 10, найти минимумы и максимумы
# Ваш код здесь


In [67]:
a = np.random.random((10, 10))
print(a.min(), a.max())

0.021225740697067286 0.9999754608729997
